### ISSUE TITLE
nothing loads

### ISSUE THREAD

**Issue by azazzel** [KuenzelIT/ulauncher-joplin#1]
using shortcut "to do" and just hangs on loading ... doesn`t display any of my notebooks 

jsonlib-python3        1.6.1
requests               2.21.0
and web clipper active..

any inputs on what I`m missing? Also I`m using several other plugins that require json and are working fine

**Comment by comod** [comment]
Same issue here.

> json lib must be installed
> requests lib must be installed
> Joplin Web Clipper service must be running

Where to find both libs? @KuenzelIT

**Comment by comod** [comment]
Ah its a Python-Thing.. After doing this

sudo apt install python
sudo apt install -y python3-pip
pip3 install jsonlib-python3==1.6.1
pip3 install requests==2.25.1

Issue already there

**Comment by azazzel** [comment]
> Ah its a Python-Thing.. After doing this
> 
> sudo apt install python
> sudo apt install -y python3-pip
> pip3 install jsonlib-python3==1.6.1
> pip3 install requests==2.25.1
> 
> Issue already there

did you manage to make it work?

**Comment by DiegoBari** [comment]
I have the same issue in Linux Mint 20.1
After type the Joplin note keyword, only see "Loading..."
Y have read the post form @comod , and install the 4 libs, but nothing happen. 🤷

**Comment by wari** [comment]
What we got from a new version of Joplin

```
{'items': 
  [{'id': 'b1d226e71e5d4f39abb45b9ed04ac876', 'parent_id': '', 'title': 'Welcome! (Desktop)'}, 
   {'id': '87e1e7c3649e400e810b28a9cc2979ef', 'parent_id': '', 'title': 'Solace'}, 
   {'id': '4a07d31981624231890cc1b892970296', 'parent_id': '', 'title': 'Welcome! (Mobile)'}, 
   {'id': 'ccce3ec72a5d4a36b72c36b109add78a', 'parent_id': '', 'title': 'Welcome! (Desktop)'}], 
'has_more': False}
```

The code expects a list here, but it's a dict.

```
  File "/home/wwahab/.local/share/ulauncher/extensions/com.github.kuenzelit.ulauncher-joplin/main.py", line 87, in on_event
    notebooks.sort(key=lambda x: x['note_count'], reverse=True)
AttributeError: 'dict' object has no attribute 'sort'
```

**Comment by gerroon** [comment]
Same problem on Debian Testing, even after installing those python libs.

**Comment by gerardbosch** [comment]
Same here, loads nothing:

![image](https://user-images.githubusercontent.com/30733556/198265048-b6b61faa-54b1-4f9f-b39b-b535bdefefdd.png)

It is no clear from the `README` what exact commands use to install the dependencies.

Is it possible to run it in console verbose mode to see any log?

**Comment by KuenzelIT** [comment]
Hey,

sorry, I switched to the albert launcher for different reasons, so I'm not using ulauncher anymore. I'm not sure if the extension still works. So the project is unfortunately not maintained anymore.

**Comment by breml** [comment]
FYI: I had a quick look into the extension and this would need some work to fix it, because:
1. Joplin no requires a security token to be sent with every request to the Web Clipper API
2. The API has changed in regards to the data structures, that are returned and fields have to be explicitly requested.
